### ISSUE TITLE
Monthly/Annualy View aren't displayed right in Blazor Server

### ISSUE THREAD

**Issue by progrobin** [tossnet/Blazor-Calendar#19]
I am using the sample code for the Blazor Server Application but the Monthly and Annual Views are not displayed right (see images below).
![Annualy](https://github.com/tossnet/Blazor-Calendar/assets/122546126/6a417b50-b12c-48ca-a027-a01da66667e2)
![Monthly](https://github.com/tossnet/Blazor-Calendar/assets/122546126/578b6e6d-f972-4592-b670-f15a8ae85fd5)

**Comment by tossnet** [comment]
I have the feeling that you're missing a declaration in the CSS file.
