### ISSUE TITLE
ID can only be an Integer

### ISSUE THREAD

**Issue by knipper6554** [tossnet/Blazor-Calendar#6]
Thank you for writing this and saving me so much time.

I actually have a couple things.

I store data as guids.  In order for the click function to work, I need the ID to be a guid.  I know I can work around it but it would be nice if that was an option.

**Comment by tossnet** [comment]
sorry, I completely forgot your message. You are right, we have to find a general solution

**Comment by tossnet** [comment]
I had a property called "Key" with string type
