### ISSUE TITLE
# of items in a given day in Monthly View

### ISSUE THREAD

**Issue by knipper6554** [tossnet/Blazor-Calendar#8]
Is there a way to edit the content to customize the display of data in a given day?

Right now, due to styling, it appears that there can only be 2 items listed on a given day.

![image](https://user-images.githubusercontent.com/112656584/205993663-378243c4-8f89-4f80-959f-37fea61f8c17.png)

There seems to be ample whitespace around the items to add at least one more item.

**Comment by tossnet** [comment]
You're right, we have to think about this
